import YAML from "yaml";
import type { VMConfig, MountSpec } from "../types.js";
import { UBUNTU_IMAGE_URL, PROJECT_MOUNT_POINT, GATEWAY_PORT } from "./constants.js";

export interface LimaYamlOptions {
  /** Whether to include port forwards for the gateway. Default: true. */
  forwardGateway?: boolean;
  /** Host port for the gateway forward. Default: GATEWAY_PORT (18789). */
  gatewayPort?: number;
  /** Extra host directories to mount into the VM. */
  extraMounts?: MountSpec[];
}

export function generateLimaYaml(config: VMConfig, options: LimaYamlOptions = {}): string {
  const { forwardGateway = true, gatewayPort, extraMounts } = options;
  const hostPort = gatewayPort ?? GATEWAY_PORT;

  const mounts: Array<{ location: string; mountPoint: string; writable: boolean }> = [
    {
      location: config.projectDir,
      mountPoint: PROJECT_MOUNT_POINT,
      writable: false,
    },
    {
      location: `${config.projectDir}/data`,
      mountPoint: `${PROJECT_MOUNT_POINT}/data`,
      writable: true,
    },
  ];

  if (extraMounts && extraMounts.length > 0) {
    for (const mount of extraMounts) {
      mounts.push({
        location: mount.location,
        mountPoint: mount.mountPoint,
        writable: mount.writable ?? false,
      });
    }
  }

  const doc: Record<string, unknown> = {
    vmType: "vz",
    os: "Linux",
    arch: "aarch64",
    images: [{ location: UBUNTU_IMAGE_URL, arch: "aarch64" }],
    cpus: config.cpus,
    memory: config.memory,
    disk: config.disk,
    mountType: "virtiofs",
    mounts,
    ssh: { localPort: 0, forwardAgent: true },
    hostResolver: { enabled: true },
  };

  if (forwardGateway) {
    doc.portForwards = [{ guestPort: GATEWAY_PORT, hostPort }];
  }

  const header = `# Generated by clawctl\n# VM: ${config.vmName}\n\n`;
  return header + YAML.stringify(doc);
}
