import dedent from "dedent";
import type { VMConfig } from "../types.js";
import { UBUNTU_IMAGE_URL, PROJECT_MOUNT_POINT, GATEWAY_PORT } from "./constants.js";

export interface LimaYamlOptions {
  /** Whether to include port forwards for the gateway. Default: true. */
  forwardGateway?: boolean;
  /** Host port for the gateway forward. Default: GATEWAY_PORT (18789). */
  gatewayPort?: number;
}

export function generateLimaYaml(config: VMConfig, options: LimaYamlOptions = {}): string {
  const { forwardGateway = true, gatewayPort } = options;
  const hostPort = gatewayPort ?? GATEWAY_PORT;

  const sections: string[] = [
    dedent`
      # Generated by clawctl
      # VM: ${config.vmName}

      vmType: vz
      os: Linux
      arch: aarch64

      images:
        - location: "${UBUNTU_IMAGE_URL}"
          arch: "aarch64"

      cpus: ${config.cpus}
      memory: "${config.memory}"
      disk: "${config.disk}"

      mountType: virtiofs
      mounts:
        - location: "${config.projectDir}"
          mountPoint: "${PROJECT_MOUNT_POINT}"
          writable: false
        - location: "${config.projectDir}/data"
          mountPoint: "${PROJECT_MOUNT_POINT}/data"
          writable: true

      ssh:
        localPort: 0
        forwardAgent: true

      hostResolver:
        enabled: true
    `,
  ];

  if (forwardGateway) {
    sections.push(
      dedent`
        portForwards:
          - guestPort: ${GATEWAY_PORT}
            hostPort: ${hostPort}
      `,
    );
  }

  return sections.join("\n") + "\n";
}
