import dedent from "dedent";
import type { VMConfig } from "../types.js";
import { UBUNTU_IMAGE_URL, PROJECT_MOUNT_POINT, GATEWAY_PORT } from "./constants.js";

export interface LimaYamlOptions {
  /** Whether to include port forwards for the gateway. Default: true. */
  forwardGateway?: boolean;
  /** Host port for the gateway forward. Default: GATEWAY_PORT (18789). */
  gatewayPort?: number;
  /** Extra host directories to mount read-only (e.g. ["~", "~/.ssh"]). */
  extraMounts?: string[];
}

/**
 * Derive the guest mount point for a host path.
 * - "~"        → "/mnt/host"
 * - "~/.ssh"   → "/mnt/host/.ssh"
 * - "/opt/data" → "/mnt/host/opt/data"
 */
export function guestMountPoint(hostPath: string): string {
  if (hostPath === "~") return "/mnt/host";
  if (hostPath.startsWith("~/")) return `/mnt/host/${hostPath.slice(2)}`;
  // Absolute path: strip leading slash and nest under /mnt/host
  return `/mnt/host/${hostPath.replace(/^\//, "")}`;
}

export function generateLimaYaml(config: VMConfig, options: LimaYamlOptions = {}): string {
  const { forwardGateway = true, gatewayPort, extraMounts } = options;
  const hostPort = gatewayPort ?? GATEWAY_PORT;

  const sections: string[] = [
    dedent`
      # Generated by clawctl
      # VM: ${config.vmName}

      vmType: vz
      os: Linux
      arch: aarch64

      images:
        - location: "${UBUNTU_IMAGE_URL}"
          arch: "aarch64"

      cpus: ${config.cpus}
      memory: "${config.memory}"
      disk: "${config.disk}"

      mountType: virtiofs
      mounts:
        - location: "${config.projectDir}"
          mountPoint: "${PROJECT_MOUNT_POINT}"
          writable: false
        - location: "${config.projectDir}/data"
          mountPoint: "${PROJECT_MOUNT_POINT}/data"
          writable: true
    `,
  ];

  // Append extra read-only mounts
  if (extraMounts && extraMounts.length > 0) {
    const mountLines = extraMounts
      .map(
        (hostPath) => dedent`
          - location: "${hostPath}"
            mountPoint: "${guestMountPoint(hostPath)}"
            writable: false
        `,
      )
      .join("\n");

    // Replace the trailing section to continue the mounts block
    sections[0] += "\n" + mountLines;
  }

  sections.push(
    dedent`
      ssh:
        localPort: 0
        forwardAgent: true

      hostResolver:
        enabled: true
    `,
  );

  if (forwardGateway) {
    sections.push(
      dedent`
        portForwards:
          - guestPort: ${GATEWAY_PORT}
            hostPort: ${hostPort}
      `,
    );
  }

  return sections.join("\n") + "\n";
}
